#{
  import "requirements.typ": drafting, glossarium, wut-thesis
  import wut-thesis: acknowledgements, appendix, figure-outline, table-outline, wut-thesis
  import "utils.typ": flex-caption-styles, glossary-outline, todo
  import "glossary.typ": glossary
  import glossarium: make-glossary, register-glossary
  import drafting: note-outline, set-margin-note-defaults

  show: make-glossary
  register-glossary(glossary)
  show: flex-caption-styles

  /** Drafting

    The "draft" variable is used to change the coloring of links, show TODOs (both in
    the thesis and TODO outline), as well as DRAFT in the header and the title. This
    should be true until the final version is handed-in.

    The "in-print" variable is used to generate a PDF file for physical printing (it adds
    bigger margins on the binding part of the page and changes the numbering placement).
    It should be set to `false` unless you want to create a version of the PDF file for
    physical print, in which case set it to `true`. To prepare a PDF file for the
    final hand-in (that is to upload it to APD/onedrive) please set this variable to
    `false`. variable to false.

  **/
  let draft = false
  let in-print = not draft
  set-margin-note-defaults(hidden: not draft)

  /// Set the languages of your studies and thesis.
  let lang = (
    /// Language in which you studied, influences the language of the titlepage.
    studies: "pl",
    /// Language in which your thesis is written, influences the rest of the text (i.e.
    /// abstracts order, captions/references supplements, hyphenation etc).
    thesis: "pl",
  )

  show: wut-thesis.with(
    draft: draft,
    in-print: in-print,
    lang: lang,
    // Adjust the following fields accordingly to your thesis
    titlepage-info: (
      thesis-type: "engineer", // or "bachelor" or "master"
      program: "Informatyka",
      specialisation: "Sztuczna Inteligencja",
      institute: "Instytut Informatyki",
      supervisor: "prof. dr hab. inż. Przemysław Rokita",
      // The optional advisor of the thesis, this will be typeset as
      //  `consultation`/`konsultacje` in the titlepage.
      advisor: none, // or `none` if there were no advisors
      faculty: "weiti", // see the tutorial section of this thesis for a list of all possible faculty shorthands
      index-number: "325190",
      date: datetime.today(), // not today: datetime(year: 1969, month: 9, day: 6,)
    ),
    // if you don't want to create a title page (e.g. if you need to use the one
    // generated by APD) then comment the above `titlepage-info` lines and instead
    // uncomment this line:
    // titlepage-info: none,
    author: "Daniel Machniak",
    // Note that regardless of the language of your thesis you need to fill in all the
    // fields below - both *.en and *.pl
    title: (
      pl: "Poprawa jakości materiałów wideo z wykorzystaniem metod sztucznej inteligencji",
      en: "Video quality enhancement using artificial intelligence methods",
    ),
    abstract: (
      en: [
        // max 1 page
        The main research area of this thesis is the enhancement of video quality using artificial intelligence methods. Given current deployment challenges and the practical significance of the problem, the final scope of the research focused on optimizing the inference of a diffusion-based video super-resolution model on memory-constrained graphics cards. Although diffusion-based models currently provide the highest image reconstruction quality, their main drawback is a substantial memory requirement, which in practice precludes running these models outside of specialized server-class hardware.

        The aim of this work was to adapt one such solution, the single-step _FlashVSR_ model @Zhuang2025FlashVSRTR, to run on a graphics card equipped with 10 GB of VRAM, while maintaining acceptable reconstruction quality and processing time. To this end, the reference implementation was refactored into a modular package and three main optimization axes were implemented: spatial and temporal tiling, integer quantization of the diffusion transformer, and interchangeable attention kernels. The performance and quality of the optimized pipeline were evaluated on footage with both synthetic and real-world degradations.

        The experiments demonstrated that spatial tiling is the key prerequisite for running the~model on resource-constrained hardware, as it is the only technique that makes peak memory usage independent of the input resolution. In turn, utilizing a different block-sparse attention variant allowed for a clear acceleration of the model. The application of~quantization translated into an additional reduction in memory consumption, although this came at the cost of longer processing time. Importantly, any potential drop in the quality of~the~generated images resulted almost entirely from the use of tiling, whereas the introduced computational optimizations remained practically neutral for reconstruction quality.
      ],
      pl: [
        Głównym obszarem badawczym pracy jest poprawa jakości materiałów wideo z wykorzystaniem metod sztucznej inteligencji. Biorąc pod uwagę aktualne wyzwania wdrożeniowe i~praktyczne znaczenie problemu, ostateczny zakres badań skoncentrowano na optymalizacji inferencji dyfuzyjnego modelu superrozdzielczości wideo na kartach graficznych o ograniczonej pamięci. Choć modele oparte na dyfuzji zapewniają obecnie najwyższą jakość rekonstrukcji obrazu, ich główną wadą jest znaczne zapotrzebowanie na pamięć, które w praktyce uniemożliwia uruchomienie tych modeli poza specjalistycznym sprzętem klasy serwerowej.

        Celem pracy było dostosowanie jednego z takich rozwiązań, jednokrokowego modelu _FlashVSR_, do działania na karcie graficznej wyposażonej w 10 GB pamięci VRAM, przy zachowaniu akceptowalnej jakości rekonstrukcji i czasu przetwarzania. W tym celu referencyjną implementację przekształcono w modułowy pakiet i wdrożono trzy główne osie optymalizacji: kafelkowanie przestrzenne i czasowe, całkowitoliczbową kwantyzację transformatora dyfuzyjnego oraz wymienne jądra mechanizmu uwagi. Wydajność oraz jakość zoptymalizowanego potoku przetestowano na nagraniach z degradacjami syntetycznymi i rzeczywistymi.

        Badania wykazały, że kluczowym warunkiem uruchomienia modelu na sprzęcie o ograniczonych zasobach jest kafelkowanie przestrzenne, które jako jedyne uniezależnia zapotrzebowanie na pamięć od rozdzielczości wejściowej. Z kolei wykorzystanie innego wariantu uwagi blokowo-rzadkiej pozwoliło wyraźnie przyspieszyć działanie modelu. Zastosowanie kwantyzacji przełożyło się na dodatkową redukcję zużycia pamięci, choć odbyło się to kosztem dłuższego czasu przetwarzania. Co istotne, ewentualny spadek jakości wygenerowanego obrazu wynikał niemal w całości z zastosowania kafelkowania, podczas gdy wprowadzone optymalizacje obliczeniowe pozostały praktycznie neutralne dla jakości rekonstrukcji.
      ],
    ),
    keywords: (
      pl: (
        "superrozdzielczość wideo",
        "modele dyfuzyjne",
        "FlashVSR",
        "kwantyzacja",
        "mechanizmy uwagi",
        "optymalizacja inferencji",
      ),
      en: (
        "video super-resolution",
        "diffusion models",
        "FlashVSR",
        "quantization",
        "attention mechanisms",
        "inference optimization",
      ),
    ),
  )

  // --- Custom Settings ---
  // if you want to override any settings from the template here is the place to do so,
  // e.g.:
  // Use Comic Sans Font
  // set text(font: "Comic Sans MS")
  // Use nicer microtypography
  set par(justification-limits: (
    tracking: (min: -0.01em, max: 0.02em),
  ))

  // --- Main Chapters ---
  include "content/Wstep.typ"
  include "content/Podstawy.typ"
  include "content/Przeglad.typ"
  include "content/WyborRozwiazan.typ"
  include "content/Projekt.typ"
  include "content/Implementacja.typ"
  include "content/Metodyka.typ"
  include "content/Wyniki.typ"
  include "content/Podsumowanie.typ"

  // --- Acknowledgements ---
  // You can put your acknowledgements (pol. podziękowania) here.
  // Below is an example containing acknowledgements for the PLGrid grant.
  // Comment out if not needed.
  // acknowledgements[
  //   We gratefully acknowledge Poland's high-performance Infrastructure PLGrid
  //   #text(fill: red)[(wybierz właściwy ośrodek z listy: ACK Cyfronet AGH, PCSS, CI TASK,
  //     WCSS)] for providing computer facilities and support within computational grant no
  //   #text(fill: red)[(numer grantu)]
  //   #todo[Numer grantu i typ ośrodka]
  // ]

  // --- Bibliography ---
  bibliography("library.bib", style: "ieee", title: "Bibliografia")

  // List of Acronyms - comment out, if not needed (no abbreviations were used).
  // glossary-outline(glossary)

  // List of figures - comment out, if not needed.
  figure-outline(lang.thesis)

  // List of tables - comment out, if not needed.
  table-outline(lang.thesis)

  // --- Appendices ---
  // Comment out if not needed.
  // appendix(lang.thesis, include "content/Appendix.typ")

  if draft {
    set heading(numbering: none)
    note-outline(title: "TODOs")
  }
}
