#{
  import "requirements.typ": drafting, glossarium, wut-thesis
  import wut-thesis: acknowledgements, appendix, figure-outline, table-outline, wut-thesis
  import "utils.typ": flex-caption-styles, glossary-outline, todo
  import "glossary.typ": glossary
  import glossarium: make-glossary, register-glossary
  import drafting: note-outline, set-margin-note-defaults

  show: make-glossary
  register-glossary(glossary)
  show: flex-caption-styles

  /** Drafting

    The "draft" variable is used to change the coloring of links, show TODOs (both in
    the thesis and TODO outline), as well as DRAFT in the header and the title. This
    should be true until the final version is handed-in.

    The "in-print" variable is used to generate a PDF file for physical printing (it adds
    bigger margins on the binding part of the page and changes the numbering placement).
    It should be set to `false` unless you want to create a version of the PDF file for
    physical print, in which case set it to `true`. To prepare a PDF file for the
    final hand-in (that is to upload it to APD/onedrive) please set this variable to
    `false`. variable to false.

  **/
  let draft = false
  let in-print = not draft
  set-margin-note-defaults(hidden: not draft)

  /// Set the languages of your studies and thesis.
  let lang = (
    /// Language in which you studied, influences the language of the titlepage.
    studies: "pl",
    /// Language in which your thesis is written, influences the rest of the text (i.e.
    /// abstracts order, captions/references supplements, hyphenation etc).
    thesis: "pl",
  )

  show: wut-thesis.with(
    draft: draft,
    in-print: in-print,
    lang: lang,
    // Adjust the following fields accordingly to your thesis
    titlepage-info: (
      thesis-type: "engineer", // or "bachelor" or "master"
      program: "Informatyka",
      specialisation: "Sztuczna Inteligencja",
      institute: "Instytut Informatyki",
      supervisor: "prof. dr hab. inż. Przemysław Rokita",
      // The optional advisor of the thesis, this will be typeset as
      //  `consultation`/`konsultacje` in the titlepage.
      advisor: none, // or `none` if there were no advisors
      faculty: "weiti", // see the tutorial section of this thesis for a list of all possible faculty shorthands
      index-number: "325190",
      date: datetime.today(), // not today: datetime(year: 1969, month: 9, day: 6,)
    ),
    // if you don't want to create a title page (e.g. if you need to use the one
    // generated by APD) then comment the above `titlepage-info` lines and instead
    // uncomment this line:
    // titlepage-info: none,
    author: "Daniel Machniak",
    // Note that regardless of the language of your thesis you need to fill in all the
    // fields below - both *.en and *.pl
    title: (
      pl: "Optymalizacja inferencji dyfuzyjnego modelu superrozdzielczości wideo na kartach graficznych o ograniczonej pamięci",
      en: "Inference optimization of a diffusion-based video super-resolution model on memory-constrained GPUs",
    ),
    abstract: (
      en: [
        // max 1 page
        Diffusion-based video super-resolution (VSR) models produce sharper and perceptually more convincing reconstructions than methods trained with pixel-wise losses, but at a substantial computational cost. Single-step models obtained through knowledge distillation, such as FlashVSR @Zhuang2025FlashVSRTR, eliminate the cost of iterative denoising but do not reduce memory consumption during a single inference pass. This is a critical issue, as required memory is the deciding factor in whether the model can be executed on a given device. FlashVSR was developed on server-grade accelerators, and its peak memory demand exceeds the budget of most consumer graphics cards, even for input resolutions significantly lower than standard recordings.

        The objective of this work is to enable the inference of a single-step, diffusion-based video super-resolution model on a graphics card equipped with 10 GB of VRAM, while maintaining acceptable reconstruction quality and processing time. To achieve this, the reference implementation of _FlashVSR_ was refactored, transforming a collection of scripts with hard-coded settings into a modular package with a fully configurable inference pipeline. Three independently switchable optimization axes were implemented: interchangeable attention kernels, covering both the dense path and the sparse-selection path; integer quantization of the diffusion transformer in weight-only and weight-and-activation variants; spatial and temporal tiling. A measurement methodology was developed, covering inference time, peak GPU memory usage, and seven quality metrics. Reconstruction quality was evaluated on two test sets: one featuring synthetic degradations and another with real-world degradations.

        It was demonstrated that the individual optimization axes play markedly different roles. Spatial tiling proved to be the necessary condition for feasibility, being the only technique that decouples peak memory usage from input resolution. Replacing the dense attention kernel brought no benefit, whereas modifying the sparse-selection mechanism shortened inference time by 12.9%. The application of quantization lowered peak memory usage by 330 MiB or 898 MiB, depending on the variant, though this came at the cost of longer processing times. The drop in reconstruction quality fell almost entirely on tiling, while the introduced computational modifications proved virtually quality-neutral on both test sets.
      ],
      pl: [
        Modele superrozdzielczości wideo (VSR) oparte na dyfuzji pozwalają uzyskać ostrzejsze i wizualnie bardziej naturalne rekonstrukcje w porównaniu do metod uczonych na podstawie błędów na poziomie pojedynczych pikseli, jednak wiąże się to ze znacznie większym kosztem obliczeniowym. Modele jednokrokowe uzyskiwane przez destylację wiedzy, takie jak _FlashVSR_ @Zhuang2025FlashVSRTR, eliminują koszt iteracyjnego odszumiania, ale nie redukują zużycia pamięci podczas pojedynczej inferencji. Jest to kluczowy problem, ponieważ to właśnie ilość wymaganej pamięci decyduje o tym, czy model może zostać uruchomiony na danym urządzeniu. Model _FlashVSR_ został opracowany na akceleratorach klasy serwerowej, a jego szczytowe zapotrzebowanie na pamięć przekracza budżet większości konsumenckich kart graficznych, nawet przy rozdzielczościach wejściowych znacznie niższych od standardowych nagrań.

        Celem pracy jest umożliwienie inferencji jednokrokowego, dyfuzyjnego modelu superrozdzielczości wideo na karcie graficznej wyposażonej w 10 GB pamięci VRAM, przy zachowaniu akceptowalnej jakości rekonstrukcji i czasu przetwarzania. W ramach realizacji tego zadania zrefaktoryzowano referencyjną implementację modelu _FlashVSR_, przekształcając zbiór skryptów o sztywnych ustawieniach w modułowy pakiet z w pełni konfigurowalnym potokiem inferencyjnym. Zaimplementowano trzy niezależnie przełączane osie optymalizacji: wymienne jądra mechanizmu uwagi, obejmujące zarówno ścieżkę gęstą, jak i ścieżkę selekcji rzadkiej; całkowitoliczbową kwantyzację transformatora dyfuzyjnego w wariantach wyłącznie dla wag oraz dla wag i aktywacji; a także przestrzenne i czasowe kafelkowanie. Opracowano metodologię pomiarową obejmującą czas inferencji, szczytowe zużycie pamięci GPU oraz siedem metryk jakości. Jakość rekonstrukcji oceniono na dwóch zbiorach testowych: jednym zawierającym degradacje syntetyczne, a drugim z degradacjami rzeczywistymi.

        Wykazano, że poszczególne osie optymalizacji odgrywają wyraźnie odmienne role. Kafelkowanie przestrzenne okazało się warunkiem koniecznym do uruchomienia modelu, ponieważ jako jedyne uniezależnia szczytowe zużycie pamięci od rozdzielczości wejściowej. Zastąpienie jądra mechanizmu uwagi dla ścieżki gęstej nie przyniosło korzyści, natomiast modyfikacja mechanizmu dla ścieżki selekcji rzadkiej pozwoliła na skrócenie czasu inferencji o 12,9%. Zastosowanie kwantyzacji obniżyło szczytowe zużycie pamięci o 330 MiB lub 898 MiB, w zależności od wariantu, jednak odbyło się to kosztem dłuższego czasu przetwarzania. Spadek jakości rekonstrukcji wynikał niemal w całości z zastosowania kafelkowania, podczas gdy wprowadzone modyfikacje obliczeniowe okazały się na obu zbiorach testowych praktycznie neutralne pod względem jakości.
      ],
    ),
    keywords: (
      pl: (
        "superrozdzielczość wideo",
        "modele dyfuzyjne",
        "FlashVSR",
        "kwantyzacja",
        "mechanizmy uwagi",
        "optymalizacja inferencji",
      ),
      en: (
        "video super-resolution",
        "diffusion models",
        "FlashVSR",
        "quantization",
        "attention mechanisms",
        "inference optimization",
      ),
    ),
  )

  // --- Custom Settings ---
  // if you want to override any settings from the template here is the place to do so,
  // e.g.:
  // Use Comic Sans Font
  // set text(font: "Comic Sans MS")
  // Use nicer microtypography
  set par(justification-limits: (
    tracking: (min: -0.01em, max: 0.02em),
  ))

  // --- Main Chapters ---
  include "content/Wstep.typ"
  include "content/Podstawy.typ"
  include "content/Przeglad.typ"
  include "content/WyborRozwiazan.typ"
  include "content/Projekt.typ"
  include "content/Implementacja.typ"
  include "content/Metodyka.typ"
  include "content/Wyniki.typ"
  include "content/Podsumowanie.typ"

  // --- Acknowledgements ---
  // You can put your acknowledgements (pol. podziękowania) here.
  // Below is an example containing acknowledgements for the PLGrid grant.
  // Comment out if not needed.
  // acknowledgements[
  //   We gratefully acknowledge Poland's high-performance Infrastructure PLGrid
  //   #text(fill: red)[(wybierz właściwy ośrodek z listy: ACK Cyfronet AGH, PCSS, CI TASK,
  //     WCSS)] for providing computer facilities and support within computational grant no
  //   #text(fill: red)[(numer grantu)]
  //   #todo[Numer grantu i typ ośrodka]
  // ]

  // --- Bibliography ---
  bibliography("library.bib", style: "ieee", title: "Bibliografia")

  // List of Acronyms - comment out, if not needed (no abbreviations were used).
  // glossary-outline(glossary)

  // List of figures - comment out, if not needed.
  figure-outline(lang.thesis)

  // List of tables - comment out, if not needed.
  table-outline(lang.thesis)

  // --- Appendices ---
  // Comment out if not needed.
  // appendix(lang.thesis, include "content/Appendix.typ")

  if draft {
    set heading(numbering: none)
    note-outline(title: "TODOs")
  }
}
